WP_CODES = ["en", "fr", "de", "es", "ja", "ru", "it", "zh", "pt", "ar", "fa", "pl", "nl", "id", "uk", "he", "sv", "cs",
            "ko", "vi", "ca", "no", "fi", "hu", "tr", "hi", "bn", "simple", "ceb", "ro", "sw", "kk", "da", "eo", "sr",
            "lt", "sk", "bg", "sl", "eu", "et", "hr", "ms", "el", "arz", "ur", "th", "ta", "te", "nn", "gl", "az", "af",
            "bs", "be", "ml", "ka", "is", "sq", "uz", "la", "br", "mk", "lv", "azb", "mr", "sh", "tl", "cy", "sco",
            "ku", "ckb", "ast", "oc", "be-tarask", "zh-yue", "hy", "pa", "my", "kn", "ne", "war", "zh-min-nan", "vo",
            "min", "lmo", "ht", "lb", "gu", "tg", "new", "bpy", "nds", "io", "pms", "su", "jv", "nap", "ba", "scn",
            "wa", "bar", "an", "ksh", "szl", "fy", "frr", "als", "ia", "ga", "yi", "mg", "gd", "vec", "ce", "sa", "mai",
            "xmf", "sd", "wuu", "as", "mrj", "mhr", "km", "roa-tara", "am", "roa-rup", "map-bms", "bh", "bcl", "co",
            "cv", "dv", "nds-nl", "fo", "hif", "fur", "gan", "glk", "gu", "hak", "ilo", "pam", "csb", "avk", "lij",
            "li", "gv", "mi", "mt", "nah", "nrm", "se", "nov", "qu", "os", "pi", "pag", "ps", "pdc", "rm", "bat-smg",
            "sc", "si", "tt", "to", "tk", "hsb", "fiu-vro", "vls", "yo", "diq", "zh-classical", "frp", "lad", "kw",
            "mn", "haw", "ang", "ln", "ie", "wo", "tpi", "crh", "nv", "jbo", "ay", "pcd", "zea", "eml", "ky", "ig",
            "or", "cbk-zam", "kg", "arc", "rmy", "ab", "gn", "so", "kab", "ug", "stq", "ha", "udm", "ext", "mzn", "pap",
            "cu", "sah", "sn", "lo", "pnb", "iu", "na", "got", "bo", "dsb", "chr", "cdo", "om", "sm", "ee", "ti", "av",
            "bm", "zu", "cr", "pih", "ss", "ve", "bi", "rw", "xh", "kl", "ik", "bug", "ts", "tn", "kv", "xal", "st",
            "bxr", "ak", "ny", "fj", "ki", "za", "ks", "ff", "lg", "rn", "chy", "mwl", "lez", "bjn", "gom", "lrc",
            "tyv", "vep", "nso", "kbd", "ltg", "rue", "pfl", "gag", "krc", "ace", "olo", "kaa", "myv", "ady", "jam",
            "tcy", "dty", "atj", "din", "lfn", "gor", "inh", "sat", "shn", "hyw", "nqo", "ban", "mnw", "szy", "awa",
            "ary", "lld", "ty", "tet", "pnt", "ch", "dz", "tum", "tw", "lbe", "sg", "koi", "mdf", "srn", "kbp", "gcr"]
